#!/usr/bin/env python

'''
emar - ar helper script
=======================

This script acts as a frontend replacement for ar. See emcc.
'''

import os, subprocess, sys
from tools import shared

DEBUG = os.environ.get('EMCC_DEBUG')

newargs = [shared.LLVM_AR] + sys.argv[1:]

if DEBUG:
  print('emar:', sys.argv, '  ==>  ', newargs, file=sys.stderr)

if len(newargs) > 2:
  subprocess.call(newargs)

